name: Build & Deploy
on:
  push:
    branches: [ main, tesis-dev ]
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: pdflatex Thesis
        uses: dante-ev/latex-action@latest
        with:
          root_file: Thesis.tex
          working_directory: document
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex Thesis
        uses: dante-ev/latex-action@latest
        with:
          root_file: Thesis.aux
          working_directory: document
          compiler: bibtex
      - name: pdflatex Thesis
        uses: dante-ev/latex-action@latest
        with:
          root_file: Thesis.tex
          working_directory: document
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Prepare for Deploy
        run: |
          mkdir build
          mv document/Thesis.pdf build/document.pdf
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
